# Detect platform
UNAME_S := $(shell uname -s)

CXX       ?= g++
LOG_LEVEL ?= 0

CXXFLAGS  ?= -std=c++17 -Wall -Wextra -O2
CPPFLAGS  ?=
CPPFLAGS  += -DLOG_LEVEL=$(LOG_LEVEL) -Iinclude -Isrc

# Platform-specific include paths (Homebrew on macOS)
ifeq ($(UNAME_S),Darwin)
CPPFLAGS  += -I/opt/homebrew/include
endif

LDFLAGS   ?=
LDLIBS    ?=

RM        := rm -f

NAME      ?= project

SRCS      := $(wildcard *.cpp) \
			 $(wildcard src/*.cpp)

OBJS      := $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(LDFLAGS) $^ $(LDLIBS) -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME) $(SINGLE_HEADER)

re: fclean all

# -----------------------------------------------------------------------------
# Single-header amalgamation
# Generates a header-only file at project root: cpp_logger.hpp
# This file contains:
#   - All public headers from include/*.hpp (with project header guards stripped)
#   - All source definitions from src/*.cpp (with local includes stripped and
#     function/constructor definitions marked inline to avoid ODR violations)
# -----------------------------------------------------------------------------

SINGLE_HEADER      := cpp_logger.hpp
HEADERS            := $(sort $(wildcard include/*.hpp))
UTILS_HEADER       := include/utils.hpp
ORDERED_HEADERS    := $(if $(wildcard $(UTILS_HEADER)),$(UTILS_HEADER) $(filter-out $(UTILS_HEADER),$(HEADERS)),$(HEADERS))
SOURCES            := $(sort $(wildcard src/*.cpp))

single_header: $(SINGLE_HEADER)

$(SINGLE_HEADER): $(ORDERED_HEADERS) $(SOURCES)
	@echo "Generating $(SINGLE_HEADER)"
	@{ \
		echo "// Amalgamated single-header for CPP-Logger"; \
		echo "// This file was generated by make single_header"; \
		echo "#ifndef CPP_LOGGER_SINGLE_HPP"; \
		echo "#define CPP_LOGGER_SINGLE_HPP"; \
		echo; \
		echo "// ---- Public headers (include/*.hpp) ----"; \
		for f in $(ORDERED_HEADERS); do \
			if [ -f "$$f" ]; then \
				echo "// ===== Begin: $$f ====="; \
				sed -E '/^[[:space:]]*#include[[:space:]]*"[^"]*"/d; \
				        /^[[:space:]]*#ifndef[[:space:]]+CPP_LOGGER_.*_HPP[[:space:]]*$$/d; \
				        /^[[:space:]]*#define[[:space:]]+CPP_LOGGER_.*_HPP[[:space:]]*$$/d; \
				        /^[[:space:]]*#endif[[:space:]]*\/\/[[:space:]]*CPP_LOGGER_.*_HPP[[:space:]]*$$/d' "$$f"; \
				echo "// ===== End: $$f ====="; \
				echo; \
			fi; \
		done; \
		echo "// ---- Sources (src/*.cpp) ----"; \
		for f in $(SOURCES); do \
			if [ -f "$$f" ]; then \
				echo "// ===== Begin: $$f ====="; \
				sed -E '/^[[:space:]]*#include[[:space:]]*"[^"]*"/d' "$$f" | \
				sed -E '/^[[:space:]]*(template|using|struct|class|namespace|#)/! s@^([[:space:]]*)([A-Za-z_][A-Za-z_0-9:<>&* ]*[[:space:]]+[A-Za-z_][A-Za-z_0-9:<>]*[[:space:]]*\(.*\)[[:space:]]*\{)@\1inline \2@'; \
				echo "// ===== End: $$f ====="; \
				echo; \
			fi; \
		done; \
		echo "#endif // CPP_LOGGER_SINGLE_HPP"; \
	} > "$(SINGLE_HEADER)"

# Test runner target: builds and runs the tests located under tests/
# The test target uses the same compiler flags as the project to ensure
# tests are built with the same configuration (including LOG_LEVEL).
TEST_BINARY := tests_runner

TEST_SRCS := tests/main/main.cpp tests/components/*/*.cpp

test: $(TEST_SRCS)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(TEST_SRCS) src/*.cpp -o $(TEST_BINARY)
	./$(TEST_BINARY)

.PHONY: all clean fclean re single_header test